var viewporter;(function(){var _viewporter;viewporter={forceDetection:false,disableLegacyAndroid:true,ACTIVE:(function(){if(viewporter.disableLegacyAndroid&&(/android 2/i).test(navigator.userAgent)){}
if((/ipad/i).test(navigator.userAgent)){return false;}
if((/webos/i).test(navigator.userAgent)){return true;}
if('ontouchstart'in window){return true;}
return false;}),READY:false,isLandscape:function(){return window.orientation===90||window.orientation===-90;},ready:function(callback){window.addEventListener('viewportready',callback,false);},change:function(callback){window.addEventListener('viewportchange',callback,false);},refresh:function(){if(_viewporter){_viewporter.prepareVisualViewport();}},preventPageScroll:function(){document.body.addEventListener('touchmove',function(event){event.preventDefault();},false);document.body.addEventListener("touchstart",function(){_viewporter.prepareVisualViewport();},false);}};viewporter.ACTIVE=viewporter.ACTIVE();if(!viewporter.ACTIVE){return;}
var _Viewporter=function(){var that=this;this.IS_ANDROID=/Android/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent);var _onReady=function(){that.prepareVisualViewport();var cachedOrientation=window.orientation;window.addEventListener('orientationchange',function(){if(window.orientation!==cachedOrientation){that.prepareVisualViewport();cachedOrientation=window.orientation;}},false);};if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',function(){_onReady();},false);}else{_onReady();}};_Viewporter.prototype={getProfile:function(){if(viewporter.forceDetection){return null;}
for(var searchTerm in viewporter.profiles){if(new RegExp(searchTerm).test(navigator.userAgent)){return viewporter.profiles[searchTerm];}}
return null;},postProcess:function(){viewporter.READY=true;this.triggerWindowEvent(!this._firstUpdateExecuted?'viewportready':'viewportchange');this._firstUpdateExecuted=true;},prepareVisualViewport:function(){var that=this;if(navigator.standalone){return this.postProcess();}
document.documentElement.style.minHeight='5000px';var startHeight=window.innerHeight;var deviceProfile=this.getProfile();var orientation=viewporter.isLandscape()?'landscape':'portrait';window.scrollTo(0,that.IS_ANDROID?1:0);var iterations=40;var check=window.setInterval(function(){window.scrollTo(0,that.IS_ANDROID?1:0);function androidProfileCheck(){return deviceProfile?window.innerHeight===deviceProfile[orientation]:false;}
function iosInnerHeightCheck(){return window.innerHeight>startHeight;}
iterations--;if((that.IS_ANDROID?androidProfileCheck():iosInnerHeightCheck())||iterations<0){document.documentElement.style.minHeight=window.innerHeight+'px';document.getElementById('viewporter').style.position='relative';document.getElementById('viewporter').style.height=window.innerHeight+'px';clearInterval(check);that.postProcess();}},10);},triggerWindowEvent:function(name){var event=document.createEvent("Event");event.initEvent(name,false,false);window.dispatchEvent(event);}};_viewporter=new _Viewporter();})();viewporter.profiles={'MZ601':{portrait:696,landscape:1176},'GT-I9000|GT-I9100|Nexus S':{portrait:508,landscape:295},'GT-P1000':{portrait:657,landscape:400},'Desire_A8181|DesireHD_A9191':{portrait:533,landscape:320}};